### ISSUE TITLE
[Thumbnail] Tweakers.net

### ISSUE THREAD

**Issue by crisp-tweakers** [andOTP/andOTP#908] opened 2021-11-03 07:57 UTC
**Name**: Tweakers
**Website**: https://tweakers.net
**Link to SVG or EPS image**: https://tweakers.net/g/if/v3/framework/tweakers_logo.svg

**Comment by flocke** [comment] 2022-02-25 04:54
Duplicate of #877

**Closed** 2022-02-25 04:54 UTC
Labels: duplicate, enhancement, thumbnail
