### ISSUE TITLE
[Thumbnail] TruckersMP

### ISSUE THREAD

**Issue by BaxAndrei** [andOTP/andOTP#938] opened 2022-01-06 12:51 UTC
**Name**: TruckersMP
**Website**: https://truckersmp.com/
**Link to SVG or EPS image**: 
[icon.zip](https://github.com/andOTP/andOTP/files/7821891/icon.zip)

**Comment by ziegenberg** [comment] 2022-01-07 20:37
Hi @BaxAndrei!

Thanks for your contribution. This issue is a duplicate of #621. Your provided EPS image is actually an embedded raster image and cannot be used in its current form.

**Closed by ziegenberg** 2022-01-07 20:37 UTC
Labels: enhancement, thumbnail
