### ISSUE TITLE
Switching to previous app after copied OTP

### ISSUE THREAD

**Issue by kinqsley** [andOTP/andOTP#584] opened 2020-06-10 10:18 UTC
Currently, there's a settings that allows to minimize andOTP app after copied OTP.
How about adding another option for switching to previous app after copied OTP from andOTP?

**Comment by flocke** [comment] 2020-06-15 04:35
> I am not really familiar with mobile programming, but I have found this and hope it helps:
> https://stackoverflow.com/questions/4038479/android-go-back-to-previous-activity

That's sadly only for returning to the previous activity of the same app (e.g. if you return from the Settings screen in andOTP back to the main screen). Navigating between different apps is a lot more restricted by the system. I never found a way to do this, which is why I put this on hold for now.

**Comment by mchllngr** [comment] 2020-10-04 10:41
I tried to solve this, but also failed in the end. Maybe my findings help someone:

In theory this setup should work for "open previous task":
```
    private void movePreviousTaskToFront() {
        ActivityManager activityManager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);

        List<ActivityManager.RunningTaskInfo> runningTaskInfoList = activityManager.getRunningTasks(2);
        int taskId = -1;
        if (runningTaskInfoList.size() >= 2) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                taskId = runningTaskInfoList.get(1).taskId;
            } else
                taskId = runningTaskInfoList.get(1).id;
        }

        if (taskId != -1) {
            activityManager.moveTaskToFront(taskId, 0, null);
        }
    }
```

The problem is `activityManager.getRunningTasks(2)`. The method is deprecated since API 21:
```
@deprecated As of {@link android.os.Build.VERSION_CODES#LOLLIPOP}, this method
is no longer available to third party
applications: the introduction of document-centric recents means
it can leak person information to the caller.  For backwards compatibility,
it will still return a small subset of its data: at least the caller's
own tasks, and possibly some other tasks
such as home that are known to not be sensitive.
```
Because of this it only returns 2 entries, the current app and the launcher. I sadly haven't found a way to retrieve the taskId for the real previous app.

**Comment by flocke** [comment] 2021-01-24 20:49
I'm closing this for now since there seems no way to do this currently.

**Closed** 2021-01-24 20:49 UTC
Labels: enhancement, help wanted
