### ISSUE TITLE
Enhancement: Add Logo for "Anydesk" (anydesk.com)

### ISSUE THREAD

**Issue by TalusUnheil** [andOTP/andOTP#655] opened 2020-09-29 12:54 UTC
Hello everybody! I would love it if you could add the logo for "Anydesk" (remote desktop software). You can find the logo here: https://anydesk.com/_static/img/favicon/anydesk_icon.png

Thanks in advance!

**Comment by meiser79** [comment] 2020-10-28 07:48
duplicate of #625

**Comment by ziegenberg** [comment] 2020-10-28 09:59
Closed as duplicate

**Comment by ziegenberg** [comment] 2020-10-28 10:02
Not a duplicate: Anydesk != Autodesk.

Therefore reopen.

**Comment by Schluggi** [comment] 2020-11-12 14:34
The logo posted by @TalusUnheil is an PNG. Here is the path for the SVG: 
https://upload.wikimedia.org/wikipedia/commons/6/60/AnyDesk-logo.svg

**Comment by ziegenberg** [comment] 2021-01-04 15:30
Finally got some time to look into this. Sorry for the delay.

**Closed** 2021-01-22 18:43 UTC
Labels: enhancement, thumbnail
