### ISSUE TITLE
All tokens wiped out on update to 0.3.1

### ISSUE THREAD

**Issue by clayt0nk** [andOTP/andOTP#91] opened 2017-12-25 09:07 UTC
I have two Fdroid-sourced installations of andOTP on two different LineageOS-based Android devices, which I keep in sync and (thankfully) use to back one another up. A few days ago I updated my primary andOTP instance, and the next time I used it, ALL of the tokens were gone, like I had installed it cleanly from the start. I do not recall (but of course cannot absolutely guarantee) I did nothing manually that would cause this erasure.

#### General information

* **App version:**
0.3.1
* **App source:** Google Play / F-Droid / GitHub / ...
FDroid
* **Android Version:**
7.1.2
* **Custom ROM:**
LineageOS 14.1-20171221

Yep, there was a Lineage OS update that happened in there somewhere too, just to complicate matters.

#### Logcat

log of update time no longer available

**Comment by RichyHBM** [comment] 2017-12-25 09:39
Most likely #16

**Comment by flocke** [comment] 2017-12-25 10:15
Yeah, from your description (and the logcat in your other bugreport) it sounds exactly like #16.

**Comment by clayt0nk** [comment] 2017-12-25 10:57
Jesus, you are right. I just stopped and restarted the app and everything is gone again.
This certainly will not fly.....

**Comment by flocke** [comment] 2017-12-25 11:01
Yeah, that bug is the most annoying one I ever encountered. And since its most likely a bug in LineageOS itself I can't really fix it.
Some people said that clearing the apps data or uninstalling and reinstalling fixed it for them, but other say even that doesn't work.

**Comment by clayt0nk** [comment] 2017-12-25 11:06
Well, halleluja, clearing data allowed me to load the JSON from the other device.
That is doable, if repeatable, though it sounds like it might not necessarily be repeatable.
If it stays put for a few days, I will try to update the other device.

**Comment by flocke** [comment] 2017-12-27 09:34
Closing because this is a duplicate of #16.

**Closed by flocke** 2017-12-27 09:34 UTC
Labels: bug, duplicate
