### ISSUE TITLE
Change thumbnail section background color

### ISSUE THREAD

**Issue by kinqsley** [andOTP/andOTP#583] opened 2020-06-10 10:08 UTC
https://raw.githubusercontent.com/flocke/andOTP/master/assets/screenshots/main_activity_dark.png

As you can see the white background color on the left side, please consider to make them transparent or follow dark/black theme color for better UI?

**Comment by flocke** [comment] 2020-06-15 04:47
Duplicate of #172.

**Closed by flocke** 2020-06-15 04:47 UTC
Labels: duplicate, enhancement
