### ISSUE TITLE
Feature Request: Show 2FA Keys

### ISSUE THREAD

**Issue by trymeouteh** [andOTP/andOTP#323] opened 2019-05-04 00:17 UTC
Please add an option to select an 2FA account and get the 2FA Key that is used for that account. Of course to get the key you should have to enter the password/pin to have the key revealed.

I use ElectronMail which is an open source email client that can allow me to access my Tutanota or ProtonMail email account. But it was a pain to get my 2FA key since I had to export my keys in a unencrypted format and open the file on my computer and read the json file to get the key which I needed to login to my email account in ElectronMail.

**Comment by flocke** [comment] 2019-05-04 05:55
Duplicate of #241, closing. But I will add the option in the new app I am writing.

**Closed** 2019-05-04 05:55 UTC
Labels: duplicate, enhancement
