### ISSUE TITLE
Cannot save otp_accounts.json on LineageOS

### ISSUE THREAD

**Issue by clayt0nk** [andOTP/andOTP#92] opened 2017-12-25 09:25 UTC
Further to issue #91:

I have two Fdroid-sourced installations of andOTP on two different LineageOS-based Android devices, which I keep in sync and (thankfully) use to back one another up. A few days ago I updated my primary andOTP instance, and the next time I used it, ALL of the tokens were gone, like I had installed it cleanly from the start.

Next step, on the old, un-updated and still perfect version of andOTP on the other device, I saved the tokens to a JSON file with the Backup (plain-text) button and copied it over to the other device. On the other device with the updated version of andOTP, I tried to import the JSON file, and absolutely nothing happened.

So I used a text editor and copied the tokens over to the new version of andOTP, one-by-one, from the JSON file. That works, and the two versions of andOTP are now in sync again.

Now I go to SAVE the JSON file in the new version, just to make sure I have a copy of both before going any further, and the result is an empty file with errors in the Android log.

#### General information

* **App version:**
0.3.1
* **App source:** Google Play / F-Droid / GitHub / ...
FDroid
* **Android Version:**
7.1.2
* **Custom ROM:**
LineageOS 14.1-20171221

Here are the log errors when I try to save the plain-text JSON:

#### Logcat
```
12-25 17:23:50.396   632 19434 I ActivityManager: START u0 {act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json cmp=com.android.documentsui/.DocumentsActivity (has extras)} from uid 10071 on display 0
12-25 17:23:50.692   632   655 I ActivityManager: Displayed com.android.documentsui/.DocumentsActivity: +272ms
12-25 17:23:50.852 17944 17944 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
12-25 17:23:51.164 21025 21025 W chromium: [WARNING:render_frame_host_impl.cc(2646)] OnDidStopLoading was called twice.
12-25 17:23:52.187 21025 21025 W chromium: [WARNING:render_frame_host_impl.cc(2646)] OnDidStopLoading was called twice.
12-25 17:23:52.654 10230 10230 W System.err: java.lang.UnsupportedOperationException
12-25 17:23:52.655 10230 10230 W System.err: 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)
12-25 17:23:52.655 10230 10230 W System.err: 	at java.security.KeyStore.getEntry(KeyStore.java:1323)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair(KeyStoreHelper.java:85)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Utilities.SecretKeyWrapper.<init>(SecretKeyWrapper.java:52)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateWrappedKey(KeyStoreHelper.java:96)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Utilities.DatabaseHelper.loadDatabase(DatabaseHelper.java:68)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Utilities.DatabaseHelper.exportAsJSON(DatabaseHelper.java:115)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Activities.BackupActivity.doBackupPlain(BackupActivity.java:402)
12-25 17:23:52.655 10230 10230 W System.err: 	at org.shadowice.flocke.andotp.Activities.BackupActivity.onActivityResult(BackupActivity.java:287)
12-25 17:23:52.655 10230 10230 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
12-25 17:23:52.655 10230 10230 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
12-25 17:23:52.655 10230 10230 W System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
12-25 17:23:52.655 10230 10230 W System.err: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
12-25 17:23:52.656 10230 10230 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
12-25 17:23:52.656 10230 10230 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-25 17:23:52.656 10230 10230 W System.err: 	at android.os.Looper.loop(Looper.java:154)
12-25 17:23:52.656 10230 10230 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-25 17:23:52.656 10230 10230 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 17:23:52.656 10230 10230 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-25 17:23:52.656 10230 10230 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-25 17:23:52.682 17817 17817 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Download/otp_accounts.json (2)
12-25 17:23:53.185 21025 21025 W chromium: [WARNING:render_frame_host_impl.cc(2646)] OnDidStopLoading was called twice.
```

**Comment by flocke** [comment] 2017-12-25 10:13
This is probably a duplicate of #16, the most annoying and random bug I ever encountered.
Did try clearing the apps data before importing the backup again?

**Comment by flocke** [comment] 2017-12-27 09:34
Closing because this is a duplicate of #16.

**Closed by flocke** 2017-12-27 09:34 UTC
Labels: bug, duplicate
