### ISSUE TITLE
Can't save edit entry

### ISSUE THREAD

**Issue by Offerel** [andOTP/andOTP#543] opened 2020-05-07 20:47 UTC
Seems to be something with the new edit box in 0.7.1 beta. If I try to change an entry, like issuer or description, the save button stays greyed out. 

But I love the feature to display the secret in this dialog. Thumbs up!

**Comment by flocke** [comment] 2020-05-08 04:46
I think I already see what the problem is and it's something really stupid. Will be fixed soon...

**Closed** 2020-05-12 04:33 UTC
Labels: bug
