### ISSUE TITLE
[Thumbnail] Jetbrains

### ISSUE THREAD

**Issue by pablotheissen** [andOTP/andOTP#822] opened 2021-05-01 05:59 UTC
**Name**: Jetbrains
**Website**: https://www.jetbrains.com/
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/1/1a/JetBrains_Logo_2016.svg

See brand guide for cropping the logo according to Jetbrains: https://www.jetbrains.com/company/brand/img/logo2.svg  / https://www.jetbrains.com/company/brand/

I created a couple of versions, hope that makes things easier for you, the last one is a vector version of the JetBrains Favicon, which may be the best fit for andOTP:
https://gist.github.com/pablotheissen/5b2e2b4099ad54af631df9be35bb2b76

**Comment by ziegenberg** [comment] 2021-05-02 12:09
The logo for JetBrains is already available since v0.7.1 and was added with 4b308aedcee2b667d55332363b59ad96e107096b.
This issue is closed as a duplicate of #436.

**Closed by ziegenberg** 2021-05-02 12:09 UTC
Labels: enhancement, thumbnail
