### ISSUE TITLE
The app reveals tokens before the fingerprint is presented

### ISSUE THREAD

**Issue by nonsleepr** [andOTP/andOTP#412] opened 2019-10-28 13:44 UTC
#### General information

* **App version:** 0.6.3.1
* **App source:** F-Droid
* **Android Version:** 10
* **Custom ROM:** Stock

#### Expected result
The app should show blank/blurred screen before the pass/fingerprint is entered/presented.

**What does happen instead?**
When the app was used (with the fingerprint) before, and then closed. When reopened after a while, it requests the fingerprint, but shows the tokens in the background.

#### Steps to reproduce
 
 * **Authentication:** Device credentials
 * **Database encryption:** Android KeyStore
 * The phone with fingerprint scanner

1. Open the app and present the fingerprint.
2. Close the app.
3. Wait for a bit (1 minute?)
4. Open the app again.

**Comment by flocke** [comment] 2019-10-29 10:39
Sounds like a duplicate of #264

**Closed by flocke** 2019-10-29 10:39 UTC
Labels: bug
