### ISSUE TITLE
Can't submit PIN, access OTPs [F-Droid]

### ISSUE THREAD

**Issue by 0xb100d** [andOTP/andOTP#87] opened 2017-12-16 00:31 UTC
I'm missing logcat because I'm currently traveling which is making this issue more serious for me. 

-----------------------------

#### General information

* **App version:0.3.0**
* **App source:** F-Droid...
* **Android Version: 6**
* **Custom ROM:Lineage 13**

#### Expected result
**What is expected?** 
I type in my PIN and it takes me to my OTPs.
**What does happen instead?**
there is no way to submit my PIN, no button, enter doesn't work, just stuck at the Pin page. Because I set the pin before I added any OTPS I think it may have something to do with the problem.
#### Logcat
```
Paste your logcat here (or use something like Pastbin for long logs)
```

#### Steps to reproduce
 
 * ...

**Comment by flocke** [comment] 2017-12-16 07:26
Just tested it and it works without problems for me. It shouldn't be a problem that you added the PIN before adding any OTPs.
Are you using a hardware keyboard? Because normally the Enter / Done key on the virtual keyboard should work (but I never tested with a hardware keyboard).

**Comment by 0xb100d** [comment] 2017-12-17 14:24
I'm not using a hardware keyboard, and pressing enter is not working for me. Is there any message displayed if the pin is incorrect? I am fairly certain I'm putting in the pin  I set, but am not getting any notification one way or another when I type in the PIN and press enter.

Is there anything else I can do to access my OTPs? I just updated the app and still no luck. Thank you!

**Comment by flocke** [comment] 2017-12-17 15:54
Sadly I can't do much without a logcat (except guessing). If the PIN you enter is wrong you should get a toast notification and the app should automatically close.
Are you using the stock LineageOS keyboard?

Sadly there is no easy way to get to your tokens. If you got a recent backup from andOTP you could decrypt it on your PC and try to import the tokens manually in another app. But that requires a lot of manual work.

**Comment by 0xb100d** [comment] 2017-12-17 15:59
I will try to get a logcat soon. I am using a different keyboard, I will try default google. Unfortunately I did not back up, since as soon as andOTP closed after first loading OTPs it asked me for PIN.
Does it mean anything that I am not getting any message or anything upon inputting the PIN? I am pretty sure it is correct, but it isn't even telling me that I've done anything wrong.

**Comment by flocke** [comment] 2017-12-17 16:10
If you press enter on the keyboard and absolutely nothing happens (not even the keyboard closes) then it is not an error with your PIN.
As a quick and dirty fix (if switching to the stock keyboard does not help) if you are rooted you can disable the authentication by manually editing the settings files.
For that take a root explorer (Amaze for example) and go to `/data/data/org.shadowice.flocke.andotp/shared_prefs` and open the file `org.shadowice.flocke.andotp_preferences.xml` (as text file). There you should see a line `<string name="pref_auth">pin</string>`. Delete that whole line and save the file. After that you should be able to open andOTP again.

**Comment by 0xb100d** [comment] 2017-12-17 16:12
Will try this now, and was exactly what I was hoping for. Really love the app (got it so that I could do backups, total failure on my part) and really appreciate your help!

**Comment by flocke** [comment] 2017-12-17 16:52
Which keyboard were you using (just so I can maybe try and reproduce this myself)?

**Comment by 0xb100d** [comment] 2017-12-17 16:54
its keyboard 69. I finally randomly got the toast error and quit, but I'm not quite sure how it decided to come up when I seem to not have done much differently.

**Comment by flocke** [comment] 2017-12-17 21:09
I just tested Keyboard 69 on my device and got the same problem. This seems like more of a keyboard error than something to do with andOTP.

**Comment by flocke** [comment] 2017-12-18 09:07
As I said that seems to be a keyboard error with Keyboard 69. The password entry is just a default Android text entry so it should work with all keyboards.
Regardless I will add a separate button to submit the PIN/Password independent of the keyboard in the next version.

**Comment by Sergi0O** [comment] 2017-12-27 22:18
To unblock the app in this situations you can edit the file "/data/data/org.shadowice.flocke.andotp/shared_prefs/org.shadowice.flocke.andotp_preferences.xml". Change the value of the string "pref_auth" form "pin" to "none". Then restart the app.

**Comment by flocke** [comment] 2018-01-08 09:40
I added an additional button to submit the password in the custom-encryption branch.
This issue will be closes once the branch gets merged.

**Closed** 2018-01-11 12:19 UTC
Labels: bug, enhancement
