### ISSUE TITLE
Support for custom thumbnail images.

### ISSUE THREAD

**Issue by wischi-chr** [andOTP/andOTP#653] opened 2020-09-25 01:30 UTC
Maybe an option to use custom images for thumbnails (like OTP+) would be a good supplement for already implemented Thumbnails.

Without a custom option the only alternative would be to hardcode thumbnails for every new service that appears.

**Comment by flocke** [comment] 2020-09-25 03:08
Duplicate of #225

**Closed** 2020-09-25 03:09 UTC
Labels: duplicate
