### ISSUE TITLE
[Thumbnail] Deutsche Bahn is missing 

### ISSUE THREAD

**Issue by shepherds-git** [andOTP/andOTP#957] opened 2022-02-20 20:34 UTC
**Name**: Deutsche Bahn
**Website**: https://www.bahn.de
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/d/d5/Deutsche_Bahn_AG-Logo.svg

**Comment by reinerh** [comment] 2022-04-30 15:24
Duplicate of #896.

**Closed** 2022-05-01 20:02 UTC
Labels: duplicate, enhancement, thumbnail
