### ISSUE TITLE
Fails to add entry via QR-Code

### ISSUE THREAD

**Issue by Masgalor** [andOTP/andOTP#195] opened 2018-06-22 16:23 UTC
#### General information

* **App version:** 0.5.0.1 & 0.6.0-beta2
* **App source:** F-Droid
* **Android Version:** 7.1.2
* **Custom ROM:** ResurrectionRemix v5.8.5

#### Expected result
**What is expected?** 
The app fails to add a new entry via scanning the qr-code.
I've added all my previous entries on version 0.4.x without any problem.
My os has not changed since then, so i assume its some internal problem.

After scanning the qr-code the error "Verschlüsselungsschlüssel nicht geladen (encryption key was not loaded)" is displayed. However I can add new entries if I configure them manually, so there seems to be no problem with encrypting the database.

**What I tried so far**
* Reset the cache
* Clear the KeyStore

#### LogCat
Im not that familiar with android debugging, so here a excessive Log.
https://pastebin.com/5419mBKB

**Comment by flocke** [comment] 2018-06-22 17:30
I'm still on vacation till Monday, after that I will have a look. I assume you use the KeyStore as encryption method?

**Comment by Masgalor** [comment] 2018-06-23 17:51
Yes I do.
But the problem does not depend on the encryption method, it is also present when password/pin is used.

**Comment by flocke** [comment] 2018-06-26 15:06
Strange, I am not able to recreate this error and the logcat doesn't show any andOTP related error messages.

**Comment by Masgalor** [comment] 2018-06-27 19:54
As I said above my knowledge about Android is very limited, so maybe my assumptions are just ridicules. But anyway, here my thoughts.

The scanned qr-code gives a string like:
otpauth://totp/<issuer>:<username>?secret=<uppercase letters and numbers>&issuer=<issuer>

I tried malformed versions of the qr-code to trigger the parameter-check errors in "/Database/Entry/public Entry(String contents)" and they worked as expected, so I'd say the zxing module returns the correct string.

The only other difference from adding an entry manually I could imagine is the fact that the main activity looses the focus to the bar-code scanner and gets it back after scanning, so the method onResume() would be called.

I don't know how the thread model of android works, but the method onResume() handles the encryption key and the database needs the key to store the changes, and that nearly at the same time.
So maybe the method to save the database needs to be delayed until the resume is completed or something like that?

However if I can get you any useful information, just tell me.

**Comment by Masgalor** [comment] 2018-06-28 19:16
Just for your information I discovered, that my problem can be solved by declaring the encryption-key as static value.

```diff
#andotp/View/EntriesCardAdapter.java
--- private SecretKey encryptionKey = null;
+++ private static SecretKey encryptionKey = null;
```

**Comment by flocke** [comment] 2018-06-29 08:28
Strange, especially since I never encountered the bug before.
But changing the key to static shouldn't be a problem. I will test it a bit and then push it and close this issue.

**Comment by Masgalor** [comment] 2019-01-24 17:13
After upgrading to a newer version of the ROM I use this issue disappeared.
So it is somehow a bug in "ResurrectionRemix v5.8.5".

**Comment by lefuglyduck** [comment] 2019-10-02 17:22
I'm getting this issue too. 

App version: 0.6.2
App source: F-Droid
Android Version: 9
Custom ROM: Descendant v4.0.1

**Comment by flocke** [comment] 2019-10-02 17:42
@lefuglyduck Is this true for every QR code or just on one site?

**Comment by lefuglyduck** [comment] 2019-10-02 18:00
I just checked and it seems to be happening on every site.

**Comment by flocke** [comment] 2019-10-02 18:01
But you can open the app and view your accounts and add new ones manually?

**Comment by flocke** [comment] 2019-10-02 18:03
That means it's not an issue with the encryption key. It just seems to forget the key while in the QR code scanner. Could you maybe record a logcat?

**Comment by lefuglyduck** [comment] 2019-10-02 18:24
[logcat.txt](https://github.com/andOTP/andOTP/files/3682712/logcat.txt)

**Comment by flocke** [comment] 2019-10-02 18:39
I'm gonna look at it tomorrow, today I only have my phone and that's kind of hard to read a logcat on...

**Comment by flocke** [comment] 2019-10-04 10:36
@lefuglyduck I can't find anything wrong in your logcat, except one KeyStore error. But since you can load the database and manually add stuff the KeyStore works at least in those cases. I have no idea why he just doesn't work when scanning QR codes. I will have to do some more research.

**Comment by quentinvernot** [comment] 2019-10-29 15:11
I stumbled upon the same bug (manual entry works but scanning the QRCode doesn't), I think I solved it: I had "Don't keep activities/Destroy every activity as soon as the user leaves it" ticked in my phone's dev settings, unticking it fixed the issue.

When you start the QRCode scan, you leave the `MainActivity`, killing `MainActivity` destroys the `EntriesCardAdapter`. When coming back from the QRCode scan, the code gets parsed, added to the list, and the program [attempts to save the DB](https://github.com/andOTP/andOTP/blob/6a1da061dd5479e08837b11a497fab82586e8b4d/app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java#L208), but the newly recreated `EntriesCardAdapter` was never given an encryptionKey and can't forward it to the underlying `DatabaseHelper` which [shows the error](https://github.com/andOTP/andOTP/blob/8da709edcfa4b46894e35284e9c96d78d28d3ddd/app/src/main/java/org/shadowice/flocke/andotp/Utilities/DatabaseHelper.java#L101) and fails.

When doing a manual entry, `ManualEntryDialog` appears in a modal and we never leave/kill `MainActivity`, which explains the difference.

So it looks like the `EntriesCardAdapter` should not be linked to `MainActivity` and have a similar lifecycle to the app itself.

As a sidenote, ticking "Don't keep activities" also means that going to app's settings and back forces you to re-enter your PIN/password, which looked weird as well, so it looks like this was not intended either.

Cheers!

**Comment by flocke** [comment] 2019-10-29 17:11
@quentinvernot Thank you for investigating. I already assumed it was something like this.

In the long run I plan to solve this similar to different apps like Aegis or Cryptomator which use a kind of service with a permanent notification in the background to keep the database/vault unlocked as long as the app is running. That way it would not be coupled to a specific activity. But that requires big changes in a lot of places so it will take a while until I get to it.

**Comment by dkiessling** [comment] 2020-04-13 11:02
## General Information

- andOTP version: 0.7.0-play and 0.7.0 (from f-droid)
- Android version: 10
- Standard ROM for Nokia 7 Plus

I have the same problem with scanning the qr code for https://www.immobilienscout24.de.
The toast message is "Ungültiger QR-Code".
The same code works in Google Authenticator (com.google.android.apps.authenticator2).

The scanned qr code gives a string like:
otpauth://totp/ImmobilienScout24.de?secret=<uppercase letters and numbers, 16 digits>

**Comment by flocke** [comment] 2021-03-03 19:50
Not able to reproduce and no new reports for almost 10 months, closing.

**Closed by flocke** 2021-03-03 19:50 UTC
Labels: bug, help wanted, more information required
