### ISSUE TITLE
Save button should be always disabled until a secret key is entered

### ISSUE THREAD

**Issue by enwokoma** [andOTP/andOTP#82] opened 2017-12-05 16:37 UTC
When I try to mess around with the app by clicking on Save without actually inputting the secret key, the app just crashes and trying to restart the app, it keeps crashing on startup, so only option is to clear the app's data which shouldn't be so, I think it's rather better to maybe disable the save button when the edittext fields are still empty so as to prevent the crash from happening for people that might click save button by mistake!

**Comment by RichyHBM** [comment] 2017-12-05 16:44
Hmm, that's odd, not crashing for me with empty secret

**Comment by enwokoma** [comment] 2017-12-05 16:48
Hmmm.. Mine is Lollipop, tried on lollipop?

**Comment by RichyHBM** [comment] 2017-12-05 17:21
I'm on nougat

**Comment by enwokoma** [comment] 2017-12-05 18:09
Ouch! Try running on AVD with lollipop

**Comment by enwokoma** [comment] 2017-12-05 18:11
Well, anyways, I honestly think disabling the save button on default would be an enhancement just in case this crash issue happens on just lollipop. For me? I think it is nicer that way!

**Comment by flocke** [comment] 2017-12-06 06:26
Just tried it in a Lollipop AVD and can confirm that it is crashing.
Disabling save until a secret is entered should be easily done, I will push something later today.

**Comment by flocke** [comment] 2017-12-06 06:39
After some further digging I can say the crash is not caused by the empty secret. An empty secret works fine (you get a token with just zeros from that). Tested on Lollipop and Nougat AVDs.

@enwokoma Did you by any chance also not input a label, if yes then this is what caused the crash. If no I would love a logcat.

@RichyHBM An empty label causes a crash in the LetterBitmap class.

**Comment by flocke** [comment] 2017-12-06 06:42
I will push something anyways to disable the save button until a label and a secret is entered.
Since it does not really make sense to add an entry without both ...

**Comment by RichyHBM** [comment] 2017-12-06 13:08
I'm right in saying the thumbnails isn't out on the play store yet, right?

**Comment by flocke** [comment] 2017-12-06 13:10
True ... haven't thought about that.

In that case I was unable to reproduce this, when I set a label (to avoid the thumbnail crash) and no secret it works on Lollipop and Nougat as well.

@enwokoma Could you post a logcat of the crash?

**Comment by flocke** [comment] 2017-12-06 14:19
I'm closing this, as I have implemented the check if label and secret are empty.
But I would love a logcat from @enwokoma to see what the problem was (as I wasn't able to reproduce it in an AVD with Lollipop and Nougat).

**Closed by flocke** 2017-12-06 14:19 UTC

**Comment by enwokoma** [comment] 2017-12-06 17:18
Ok.. Sure! When I get home, I would post a logcat!

**Comment by enwokoma** [comment] 2017-12-07 09:35
So, Good Day!
I've managed to narrow down the logcat as to the time of the crash and this
is what I got!

127-07 08:54:30.942 20518-20518/? E/SpannableStringBuilder:
SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have zero length

**Comment by flocke** [comment] 2017-12-07 10:17
@enwokoma Could you maybe post the full logcat. Only one error makes it kind of hard to debug.
And are you trying this on a Samsung phone with TouchWiz or using a different keyboard app?

**Comment by enwokoma** [comment] 2017-12-07 11:58
Am using swiftkey keyboard on OnePlus 5T

On Dec 7, 2017 11:17, "Jakob Nixdorf" <notifications@github.com> wrote:

@enwokoma <https://github.com/enwokoma> Could you maybe post the full
logcat. Only one error makes it kind of hard to debug.
And are you trying this on a Samsung phone with TouchWiz or using a
different keyboard app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/andOTP/andOTP/issues/82#issuecomment-349924075>, or mute
the thread

**Comment by enwokoma** [comment] 2017-12-07 11:58
I would try copying and pasting the full logcat later today as requested.

On Dec 7, 2017 12:57, nwokomaemmanuel@gmail.com wrote:

Am using swiftkey keyboard on OnePlus 5T

On Dec 7, 2017 11:17, "Jakob Nixdorf" <notifications@github.com> wrote:

@enwokoma <https://github.com/enwokoma> Could you maybe post the full
logcat. Only one error makes it kind of hard to debug.
And are you trying this on a Samsung phone with TouchWiz or using a
different keyboard app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/andOTP/andOTP/issues/82#issuecomment-349924075>, or mute
the thread

**Comment by flocke** [comment] 2017-12-07 12:02
@enwokoma That would be nice. Please use pastebin or something like that, a full logcat is a little to much to copy & paste here directly.

**Comment by enwokoma** [comment] 2017-12-07 12:11
Ah ha.
I would check out pastebin!

**Comment by enwokoma** [comment] 2017-12-07 13:14
Ok.. Just returned from school and had to handle lots of client work.. Here is the full logcat as you requested for me to use pastebin..
[logcatfull.txt](https://github.com/andOTP/andOTP/files/1539152/logcatfull.txt)
