### ISSUE TITLE
[Thumbnail] UptimeRobot

### ISSUE THREAD

**Issue by silviuvulcan** [andOTP/andOTP#818] opened 2021-04-28 08:19 UTC
**Name**: UptimeRobot
**Website**: https://uptimerobot.com/
**Link to SVG or EPS image**: https://superbig.co/uploads/images/icons/icon-uptimerobot.svg

**Comment by krisu5** [comment] 2021-04-29 12:21
Logo in the "Link to SVG or EPS image" section is not official one.

Logo officially is either just the green dot or green dot with text. https://uptimerobot.com/assets/images/uptimerobot-logo.svg

**Comment by ziegenberg** [comment] 2021-04-29 12:54
This is a duplicate of #459. Therefore I will close it and transfer the updated information to #459.

**Closed by ziegenberg** 2021-04-29 12:54 UTC
Labels: duplicate, enhancement, thumbnail
