### ISSUE TITLE
Can't open app after system update

### ISSUE THREAD

**Issue by j0k2r** [andOTP/andOTP#140] opened 2018-02-22 10:37 UTC
#### General information

* **App version:** 0.4.0.1
* **App source:** F-Droid
* **Android Version:** 7.1.2
* **Custom ROM:** LineageOS 14.1.20180220

#### Expected result
**What is expected?**  
Application launched

**What does happen instead?**
Application crash

#### Logcat
```
02-22 11:23:32.707  4894  7188 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.shadowice.flocke.andotp/.Activities.MainActivity (has extras)} from uid 10028 on display 0
02-22 11:23:32.773  4894  4911 I ActivityManager: Start proc 5303:org.shadowice.flocke.andotp/u0a91 for activity org.shadowice.flocke.andotp/.Activities.MainActivity
02-22 11:23:32.785  4894  4894 D ZenLog  : intercepted: 0|android|17039403|null|1000,alarmsOnly
02-22 11:23:32.786  4894  4894 V NotificationService: pkg=android canInterrupt=false intercept=true
02-22 11:23:32.805  5303  5303 I art     : Starting a blocking GC AddRemoveAppImageSpace
02-22 11:23:32.808  5303  5303 W System  : ClassLoader referenced unknown path: /data/app/org.shadowice.flocke.andotp-1/lib/arm
02-22 11:23:32.922  5303  5303 D AndroidRuntime: Shutting down VM
02-22 11:23:32.923  5303  5303 E AndroidRuntime: FATAL EXCEPTION: main
02-22 11:23:32.923  5303  5303 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 5303
02-22 11:23:32.923  5303  5303 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}: java.lang.UnsupportedOperationException
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3454)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at java.security.KeyStore.getEntry(KeyStore.java:1323)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair(KeyStoreHelper.java:99)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadEncryptionKeyFromKeyStore(KeyStoreHelper.java:111)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at org.shadowice.flocke.andotp.Activities.MainActivity.updateEncryption(MainActivity.java:413)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at org.shadowice.flocke.andotp.Activities.MainActivity.onResume(MainActivity.java:324)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6788)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
02-22 11:23:32.923  5303  5303 E AndroidRuntime: 	... 10 more
02-22 11:23:32.926  4894  6470 W ActivityManager:   Force finishing activity org.shadowice.flocke.andotp/.Activities.MainActivity
02-22 11:23:32.969  4894  7930 I OpenGLRenderer: Initialized EGL, version 1.4
02-22 11:23:32.969  4894  7930 D OpenGLRenderer: Swap behavior 1
02-22 11:23:33.429  4894  4952 W ActivityManager: Activity pause timeout for ActivityRecord{e9cab99 u0 org.shadowice.flocke.andotp/.Activities.MainActivity t5525 f}
02-22 11:23:33.900  4894  4984 W WindowManager: Failed looking up window
02-22 11:23:33.900  4894  4984 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@5c75b36 does not exist
02-22 11:23:33.900  4894  4984 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9469)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9460)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2401)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:202)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5923)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3629)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at android.os.Looper.loop(Looper.java:154)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-22 11:23:33.900  4894  4984 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

#### Steps to reproduce
 
 * Open application

**Comment by flocke** [comment] 2018-02-22 11:23
This is #16. Known bug in LineageOS 14.1 (they do something funky with the KeyStore during a ROM update).

**Comment by flocke** [comment] 2018-02-22 11:24
Closing because this is a duplicate of #16.

**Closed by flocke** 2018-02-22 11:24 UTC
Labels: KeyStore, bug, duplicate, upstream bug
