### ISSUE TITLE
Clicking on a code-button exactly when the timer runs out reveals the first button in the list

### ISSUE THREAD

**Issue by ForGorNorPor** [andOTP/andOTP#644] opened 2020-09-15 06:57 UTC
Whenever I select any button of my list exactly at that moment when the timer runs out, the first button gets selected instead.

**Comment by flocke** [comment] 2021-03-11 19:20
I can't reproduce this any more.

This most likely had something to do with the redrawing of the entries when the time runs out.
In that case it probably got fixed with 283fb5630de72de3e95af8d2118978dffc540e19 and I can't reproduce it because of this.

Feel free to reopen if it still happens with version 0.8.1

**Closed by flocke** 2021-03-11 19:20 UTC
Labels: bug, help wanted
